[package]
authors = ["Jean-Marie Comets <jean.marie.comets@gmail.com>"]
name = "merkle-tree"
version = "0.1.0"

[dependencies]
itertools = "0.7.6"
tiger = { git = "https://github.com/jmcomets/hashes.git", branch = "tiger" }
generic-array = "*"
